# Workbook 01

---
The following problem set will focus on the lessons on Python and basic string manipulation. Answer the following guide questions by writing functions or code in cells that accomplish the requirements.

#### **1. Write a function to check whether a string is a palindrome.** (A palindrome is a string that reads the same forwards and backwards) 1 pt ####
---

In [19]:
def palindrome_test(string):
    rev = string[::-1].lower()
    if string == rev:
        print(f'"{string}" is a palindrome')
    else:
        print(f'"{string}" is not a palindrome')
    
palindrome_test('reviver')
palindrome_test('Racecar')
palindrome_test('it is not')
palindrome_test('123454321')

"reviver" is a palindrome
"Racecar" is not a palindrome
"it is not" is not a palindrome
"123454321" is a palindrome


#### **2. Write a function that checks whether a number is prime or not** 1 pt. ####
---

In [20]:
from math import sqrt

def prime_test(num):
    if num > 1:
        for i in range(2, int(sqrt(num)) + 1):
            if num % i == 0:
                print(f'{num} is not prime')
                break
        else:
            print(f'{num} is prime')
    else:
        print(f'{num} is neither prime nor composite')
                      
prime_test(0)
prime_test(-1)
prime_test(1)
prime_test(2)
prime_test(1039)
prime_test(1043)  

0 is neither prime nor composite
-1 is neither prime nor composite
1 is neither prime nor composite
2 is prime
1039 is prime
1043 is not prime


#### **3. Load `data/allstar.txt` and create a dictionary where the keys are the verses or chorus numbers, and the values are the chords for that part of the song.** 4 pts. ####
`{ "verse1": "Am, C, D, G, F, G, G, Bm", "chorus1": "C, Am, G, D, C, Am, G, D, C"..}`


#### **4. Build a dictionary from `data/allstar.txt` where the keys are the unique words, and the values are the number of times the word appeared in the song.** 4 pts. ####

#### **5. Load `Rick Astley - Never Gonna Give You Up Lyrics _ AZLyrics.com.html` and find out the ff (show the code):** 10 pts. ####
- How many unique words are there?
- List what will Rick Astley never do?
- Write a function that lists all the unique words and counts the num of occurences. Output the result as a dictionary similar to **Item 4.**
- Use the dictionary from above to create a word count histogram.

#### **6.Create a function that takes in 3 parameters (integer n, integer a, integer b), and generates an nxn numpy matrix with random values from the range a to b inclusive.** 2 pts. ####
---

In [21]:
import numpy as np

def numpy_array(size, lower_bound, upper_bound):
    if lower_bound <= upper_bound:
        array = np.random.randint(lower_bound, upper_bound + 1, size=(size, size))
        print(array)
    else:
        raise ValueError(f'Lower bound must be less than or equal to upper bound')
        
numpy_array(4,1,5)
# numpy_array(4,6,5)

[[4 2 4 1]
 [2 5 4 5]
 [5 5 2 2]
 [4 3 5 1]]


#### **7. Create a 5x5 identity matrix** (1pt) ####

In [22]:
mx = [[1 if i == j else 0 for j in range(5)] for i in range(5)]
mx

[[1, 0, 0, 0, 0],
 [0, 1, 0, 0, 0],
 [0, 0, 1, 0, 0],
 [0, 0, 0, 1, 0],
 [0, 0, 0, 0, 1]]

#### **8. Create a function that lists the first n prime numbers** (2pts) ####

In [24]:
def prime_list(count):
    primes = []
    num = 2
    while len(primes) < count:
        for i in primes:
            if num % i == 0:
                break
        else:
            primes += [num]
        num += 1
    return primes

print(prime_list(0))
print(prime_list(1))
print(prime_list(10))

[]
[2]
[2, 3, 5, 7, 11, 13, 17, 19, 23, 29]
