# Workbook 01

---
The following problem set will focus on the lessons on Python and basic string manipulation. Answer the following guide questions by writing functions or code in cells that accomplish the requirements.

1. Write a function to check whether a string is a palindrome. (A palindrome is a string that reads the same forwards and backwards) **1 pt.**

2. Write a function that checks whether a number is prime or not **1 pt.**

3. Load `data/allstar.txt` and create a dictionary where the keys are the verses or chorus numbers, and the values are the chords for that part of the song. **4 pts.**
`{ "verse1": "Am, C, D, G, F, G, G, Bm", "chorus1": "C, Am, G, D, C, Am, G, D, C"..}`

4. Build a dictionary from `data/allstar.txt` where the keys are the unique words, and the values are the number of times the word appeared in the song. **4 pts.**

5. Load `Rick Astley - Never Gonna Give You Up Lyrics _ AZLyrics.com.html` and find out the ff (show the code): **10 pts.**
       - How many unique words are there?
       - List what will Rick Astley never do?
       - Write a function that lists all the unique words and counts the num of occurences. Output the result as a dictionary similar to **Item 4.**
       - Use the dictionary from above to create a word count histogram.
       
6. Create a function that takes in 3 parameters (integer n, integer a, integer b), and generates an nxn numpy matrix with random values from the range a to b inclusive. **2 pts.**
       
7. Create a 5x5 identity matrix **(1pt)**

8. Create a function that lists the first n prime numbers **(2pts)**


# Exploration Data Analysis Assignment 1
#### Mannix Tapawan - MLE

### 1. Write a function to check whether a string is a palindrome. (A palindrome is a string that reads the same forwards and backwards

In [4]:
string = input("Enter a string: ")


def isPalindrome(s):
    """Checks if a string is a palindrome

    Parameters:
        s = input string to be checked
    """
    if s == s[::-1]:
        print(f"{s} is a palinedrome!")
    else:
        print(f"{s} is not a palindrome!")


isPalindrome(string)

Enter a string:  racecar


racecar is a palinedrome!


### 2. Write a function that checks whether a number is prime or not

In [5]:
number = int(input("Enter a number: "))


def isPrime(x):
    """Checks if a number is prime

    Parameters:
        x = number to be checked
    """
    if x > 1:
        for i in range(2, int(x / 2) + 1):
            if x % i == 0:
                print(x, "is not prime")
                break
        else:
            print(x, "is prime")
    else:
        print(x, "is not prime")


isPrime(number)


Enter a number:  17


17 is prime


### 3. Load data/allstar.txt and create a dictionary where the keys are the verses or chorus numbers, and the values are the chords for that part of the song. 4 pts. { "verse1": "Am, C, D, G, F, G, G, Bm", "chorus1": "C, Am, G, D, C, Am, G, D, C"..}

### 4. Build a dictionary from data/allstar.txt where the keys are the unique words, and the values are the number of times the word appeared in the song

### 5. Load Rick Astley - Never Gonna Give You Up Lyrics _ AZLyrics.com.html and find out the ff (show the code): 10 pts.

- How many unique words are there?
- List what will Rick Astley never do?
- Write a function that lists all the unique words and counts the num of occurences. Output the result as a dictionary similar to **Item 4.**
- Use the dictionary from above to create a word count histogram.

### 6. Create a function that takes in 3 parameters (integer n, integer a, integer b), and generates an nxn numpy matrix with random values from the range a to b inclusive.

In [3]:
import numpy as np

n = int(input("Enter matrix size: "))
a = int(input("Enter floor of range: "))
b = int(input("Enter ceiling of range: "))


def numpyMatrix(n, a, b):
    """Creates a matrix of a desired size that ha
    random values from a given range

    Parameters:
        n = size of matrix (n x n)
        a = range lower limit
        b = range upper limit
    """
    print(np.random.randint(low=a, high=b + 1, size=(n, n)))


numpyMatrix(n, a, b)

Enter matrix size:  4
Enter floor of range:  1
Enter ceiling of range:  5


[[2 3 4 4]
 [5 3 5 5]
 [4 3 2 1]
 [2 3 2 2]]


### 7. Create a 5x5 identity matrix

In [1]:
import numpy as np


def identityMatrix():
    # Prints a 5x5 identity matrix
    print(np.identity(5, dtype=int))


identityMatrix()

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]


### 8. Create a function that lists the first n prime numbers

In [2]:
number = int(input("Enter the number: "))
n = int(input("Enter the number of prime factors: "))


def nPrimeFactors(num, n):
    """List a number (n) of prime factors

    Parameters:
        num = number
        n = number of prime factors
    """
    i = 2
    ctr = 0
    while num > 1:
        if num % i == 0:
            print(i)
            num /= i
            ctr += 1
        else:
            i += 1
    
    while ctr < n:
        print('N')
        ctr += 1


nPrimeFactors(number, n)

Enter the number:  60
Enter the number of prime factors:  6


2
2
3
5
N
N
